[project]
name = "em27-retrieval-pipeline"
version = "0.1.0"
description = "automated EM27 data processing"
authors = [
    { name = "Moritz Makowski", email = "moritz.makowski@tum.de" },
    { name = "Andreas Luther", email = "andreas.luther@tum.de" },
    { name = "Marlon Müller", email = "marlon.mueller@tum.de" },
    { name = "Vyas Giridhard", email = "vyas.giridharan@tum.de" },
]
dependencies = [
    "requests>=2.31.0",
    "rich>=13.7.0",
    "click>=8.1.7",
    "filelock>=3.13.1",
    "scipy>=1.11.4",
    "compact-json>=1.6.1",
    "jsonref>=1.1.0",
    "pendulum>=2.1.2",
    "pydantic>=2.5.3",
    "polars>=0.20.5",
    "tum-esm-utils>=1.8.0",
    "em27-metadata>=1.0.0rc6",
    # the following dependencies are
    # used by the Proffast Pylot only
    "numpy>=1.26.3",
    "tqdm>=4.66.1",
    "pandas>=1.5.3",
    "pytz>=2022.7.1",
    "timezonefinder>=6.2.0",
    "pyyaml>=6.0.1",
    "fortranformat>=1.2.2",
]
requires-python = "==3.11.*"
readme = "README.md"
license = { text = "MIT" }


[project.optional-dependencies]
dev = [
    "pytest>=7.4.4",
    "types-requests>=2.31.0.20240106",
    "pytest-cov>=4.1.0",
    "python-dotenv>=1.0.0",
    "mypy>=1.8.0",
    "matplotlib>=3.8.2",
    "pyarrow>=14.0.2",
    "tailwind-colors>=1.2.1",
    "pytest-order>=1.2.0",
    "yapf>=0.40.2",
]

[tool.pdm]
distribution = false

# using pytest markers from the `pytest-order` library, we run the
# quick tests before the retrieval tests to fail fast
[tool.pytest.ini_options]
markers = [
    "integration: can only be run on a configured system",
    "quick: can be run in a CI environment, < 1 min, everything except running actual retrievals",
    "ci: can be run in a CI environment, ~ 3 min, run the complete tests but without running the actual retrieval algorithms",
    "complete: can be run in a CI environment, ~ 10 - 20 minutes, runs three sample days from different instruments and locations for every retrieval algorithm and every atmospheric profile",
]

[tool.mypy]
strict = true
implicit_reexport = true
plugins = ["pydantic.mypy"]

[tool.yapf]
based_on_style = "facebook"
coalesce_brackets = true
split_before_dict_set_generator = true
each_dict_entry_on_separate_line = false
spaces_around_subscript_colon = true

[[tool.mypy.overrides]]
module = ["src.prfpylot.prfpylot.pylot", "scipy", "scipy.signal", "polars"]
ignore_missing_imports = true
