[tool.poetry]
name = "automated-retrieval-pipeline"
version = "0.1.0"
description = ""
authors = [
    "Moritz Makowski <moritz.makowski@tum.de>",
    "Andreas Luther <andreas.luther@tum.de>",
    "Marlon Müller <marlon.mueller@tum.de>",
    "Dmytro Polityka <dmytro.polityka@tum.de>",
    "Vyas Giridhard <vyas.giridharan@tum.de>"
]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.9.*"
tum-esm-utils = "^1.0.0"
tum-esm-em27-metadata = "^1.0.0"
pydantic = "^1.10.4"
requests = "^2.28.2"
rich = "^13.2.0"
click = "^8.1.3"
filelock = "^3.9.0"
polars = "^0.16.16"
pandas = "^1.5.3"
scipy = "^1.10.1"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
pytest = "^7.2.1"
types-requests = "^2.28.11.8"
pytest-cov = "^4.0.0"
python-dotenv = "^0.21.1"
mypy = "^1.1.1"
matplotlib = "^3.7.1"
pyarrow = "^11.0.0"
tailwind-colors = "^1.0.0"


[tool.poetry.group.prfpylot.dependencies]
numpy = "^1.24.2"
tqdm = "^4.65.0"
requests = "^2.28.2"
fortranformat = "^1.2.2"
pandas = "^1.5.3"
pytz = "^2022.7.1"
timezonefinder = "^6.1.10"
pyyaml = "^6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
markers = [
    "ci: can be run in a CI environment",
    "integration: can only be run on a configured system",
]

[tool.mypy]
strict = true
implicit_reexport = true
no_warn_unused_ignores = true
plugins = ["pydantic.mypy"]

[[tool.mypy.overrides]]
module = [
    "src.prfpylot.prfpylot.pylot",
    "scipy.signal",
    "polars",
]
ignore_missing_imports = true
