[tool.poetry]
name = "em27-retrieval-pipeline"
version = "0.1.0"
description = ""
authors = [
    "Moritz Makowski <moritz.makowski@tum.de>",
    "Marlon Müller <marlon.mueller@tum.de>",
    "Vyas Giridhard <vyas.giridharan@tum.de>",
    "Andreas Luther <andreas.luther@tum.de>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.*"
requests = "^2.31.0"
rich = "^13.5.2"
click = "^8.1.6"
filelock = "^3.12.2"
pandas = "^1.5.3"
scipy = "^1.11.1"
compact-json = "^1.5.2"
jsonref = "^1.1.0"
pydantic = "^2.1.1"
pendulum = "^2.1.2"
tum-esm-em27-metadata = "2.0.0-rc.12"
tum-esm-utils = "^1.5.4"
polars = "^0.19.3"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
types-requests = "^2.31.0.2"
pytest-cov = "^4.1.0"
python-dotenv = "^0.21.1"
mypy = "^1.4.1"
matplotlib = "^3.7.2"
pyarrow = "^11.0.0"
tailwind-colors = "^1.2.1"
pytest-order = "^1.1.0"
yapf = "^0.40.2"

[tool.poetry.group.prfpylot.dependencies]
numpy = "^1.24.2"
tqdm = "^4.65.0"
requests = "^2.31.0"
fortranformat = "^1.2.2"
pandas = "^1.5.3"
pytz = "^2022.7.1"
timezonefinder = "^6.2.0"
pyyaml = "^6.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# we made sure to run the quick test suit before the retrieval tests to fail fast
[tool.pytest.ini_options]
markers = [
    "integration: can only be run on a configured system",
    "ci_quick: can be run in a CI environment, < 1 min, everything except running actual retrievals",
    "ci_intensive: can be run in a CI environment, ~ 20 min, runs one sample day for every retrieval algorithm",
    "ci_complete: can be run in a CI environment, ~ 60 min, runs three sample days for every retrieval algorithm with data from different instruments and locations",
]

[tool.mypy]
strict = true
implicit_reexport = true
no_warn_unused_ignores = true
plugins = ["pydantic.mypy"]

[tool.yapf]
based_on_style = "facebook"
coalesce_brackets = true
split_before_dict_set_generator = true
each_dict_entry_on_separate_line = false
spaces_around_subscript_colon = true

[[tool.mypy.overrides]]
module = ["src.prfpylot.prfpylot.pylot", "scipy.signal", "polars"]
ignore_missing_imports = true
